name: Update Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update site
      run: |
         curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to DEST
         ./just copy
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
         commit_message: Update "docs"
         commit_options: '--no-verify'
         push_options: '--force'
         skip_dirty_check: true
