name: Update Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Update site
      run: |
         (rm just || :) >/dev/null 2>&1 && curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to .
         ./just generate
         ./just copy

         #[ -z "$(git status --porcelain)" ] \
         # && echo https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/cancel \
         # && curl https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/cancel \
         # -X POST \
         # --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
         # --header "Content-Type: application/json" \
         # --header "User-Agent: actions/cancel-action" \
         #   && echo attempted to cancel action
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
         commit_message: Update "docs"
         commit_options: '--no-verify'
         push_options: '--force'
         skip_dirty_check: true
